title: Dongwook Kim (he/him)
logo: /assets/images/image.jpg
email: kim01444@umn.edu
cv: /assets/cv/CV_kim.pdf
gs: #about
about: #about
projects: #projects-and-publications/working-papers
awards: #awards
agenda: #agenda-on-teaching-and-research
Service: #community-service
news: #news
teaching: #teaching
theme: jekyll-theme-minimal